# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e5b7a4ff91756c3fc0d761d7b20d84adc6ef6804f1ffe1ae488d545d0eb192c96d37b0e7586f9062470464ed007d8fcfabd0bcc5c07969a817cf11dc2f9a3a2

test:
  secret_key_base: bea6240c23fd80283a962057607f23012278f815accfd3cfa8124f0ee44458bc9abb686fbc96d9e96ea23aa459e6bdc543235d8c2abd7c04e972fb3640de632b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
